/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package io.fp.campuszuhause;

public class App {

    public static void main(String[] args) {
        Professor prof1 = new Professor(40, "schmollinger", "Informatik");
        Assistent assist1 = new Assistent(24, "luca", prof1);
        Fakultaet fak1 = new Fakultaet("inf");
        fak1.addProf(prof1);
        fak1.gibAssistentZuProf(prof1);
    }
}
