/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package io.fp;
import java.util.Scanner;

public class App {

    public static void main(String[] args) {
        PrimeGame p=new PrimeGame();
        try (Scanner s = new Scanner(System.in)) {
            System.out.println("Prim Zahlen Spiel beginnt:");
            System.out.println("Raten sie ob es sich um eine Primzahl handlet oder nicht");
            int score=0;
            for(int i=1;i<6;i++){
                p.currentNextNumber();
                System.out.println("Ist " + p.getCurrentNumber() + " eine Primzahl?");
                String input=s.nextLine();
                    if(PrimeGame.isPrime(p.getCurrentNumber()))
                    {
                        if(input.equals("y")||input.equals("yes")||input.equals("j")||input.equals("ja")||input.equals("ye")) 
                        {System.out.println("Richtig! " + p.getCurrentNumber() + " ist eine Primzahl");
                        score++;
                        }
                        else System.out.println("Falsch! Bist du dumm? " + p.getCurrentNumber() + " ist eine Primzahl");
                        
                    }
                    if(!(PrimeGame.isPrime(p.getCurrentNumber())))
                    {
                        if(input.equals("n")||input.equals("no")||input.equals("nein")||input.equals("nee")||input.equals("nei")) 
                        {System.out.println("Richtig! " + p.getCurrentNumber() + " ist keine Primzahl");
                        score++;
                        }
                        else System.out.println("Falsch! Bist du dumm? " + + p.getCurrentNumber() + " ist keine Primzahl");          
                    }
            }
            try{p.nextCurrentLevel();}
            catch(Exception e)
            { e.getMessage();}
            for(int i=1;i<6;i++){
                p.currentNextNumber();
                System.out.println("Ist " + p.getCurrentNumber() + " eine Primzahl?");
                String input=s.next();
                    if(PrimeGame.isPrime(p.getCurrentNumber()))
                    {
                        if(input.equals("y")||input.equals("yes")||input.equals("j")||input.equals("ja")||input.equals("ye")) 
                        {
                            System.out.println("Richtig! " + p.getCurrentNumber() + " ist eine Primzahl");
                            score++;
                        }
                        else System.out.println("Falsch! Bist du dumm? " + p.getCurrentNumber() + " ist eine Primzahl");
                        
                    }
                    if(!(PrimeGame.isPrime(p.getCurrentNumber())))
                    {
                        if(input.equals("n")||input.equals("no")||input.equals("nein")||input.equals("nee")||input.equals("nei")) 
                        {
                            System.out.println("Richtig! " + p.getCurrentNumber() + " ist keine Primzahl");
                            score++;
                        }
                        else System.out.println("Falsch! Bist du dumm? " + + p.getCurrentNumber() + " ist keine Primzahl");          
                    }
            }
            try{p.nextCurrentLevel();}
            catch(Exception e)
            { e.getMessage();}
            for(int i=1;i<6;i++){
                p.currentNextNumber();
                System.out.println("Ist " + p.getCurrentNumber() + " eine Primzahl?");
                String input=s.next();
                    if(PrimeGame.isPrime(p.getCurrentNumber()))
                    {
                        if(input.equals("y")||input.equals("yes")||input.equals("j")||input.equals("ja")||input.equals("ye")) 
                        {
                            score++;
                            System.out.println("Richtig! " + p.getCurrentNumber() + " ist eine Primzahl");
                            
                        } 
                        else System.out.println("Falsch! Bist du dumm? " + p.getCurrentNumber() + " ist eine Primzahl");
                        
                    }
                    if(!(PrimeGame.isPrime(p.getCurrentNumber())))
                    {
                        if(input.equals("n")||input.equals("no")||input.equals("nein")||input.equals("nee")||input.equals("nei")) 
                        {
                            score++;
                            System.out.println("Richtig! " + p.getCurrentNumber() + " ist keine Primzahl");
                        }
                        else System.out.println("Falsch! Bist du dumm? " + + p.getCurrentNumber() + " ist keine Primzahl");          
                    }
            }
            if(score>10) System.out.println("Spiel beendet! Du hast von 15 moeglichen Punkten " + score + " erreicht. Sehr gut!");
            else if(score>5) System.out.println("Spiel beendet! Du hast von 15 moeglichen Punkten " + score + " erreicht. Ganz Okay!");
            else if(score>0) System.out.println("Spiel beendet! Du hast von 15 moeglichen Punkten " + score + " erreicht. Du bist scheisse!");



        
         
    }

    }
}
