/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package io.fp;

public class App {

    public static void main(String[] args) {
        Circle cir1 = new Circle(20);
        Rectangle rect1 = new Rectangle(21, 10);
        Circle cir2 = new Circle(40);
        Rectangle rect2 = new Rectangle(41, 20);
        Circle cir3 = new Circle(60);
        Rectangle rect3 = new Rectangle(61, 30);
        Shape[] shapes=new Shape[10];
        shapes[0]=cir1;
        shapes[1]=rect1;
        shapes[2]=cir2;
        shapes[3]=rect2;
        shapes[4]=cir3;
        shapes[5]=rect3;
        System.out.println("Area1: " + cir1.area());
        System.out.println("Area1: " + rect1.area());
        System.out.println("Area2: " + cir2.area());
        System.out.println("Area2: " + rect2.area());
        System.out.println("Area3: " + cir3.area());
        System.out.println("Area3: " + rect3.area());
        System.out.println("AllAreas: " + Util.accumulateArea(shapes));
        System.out.println("Umfang:" + Util.accumulateCircumference(shapes));
       


        
       
    }
}
