/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package io.fp.notebook;

public class App {

    public static void main(String[] args) {
       
        Notebook<String> note1=new Notebook<>();
        Note<String> n1=new Note<>("Mathe");
        Note<String> n2=new Note<>("Informatik");
        Note<String> n3=new Note<>("English");
        note1.addNote(n1);
        note1.addNote(n2);
        note1.addNote(n3);
        note1.printToDoList();
        Notebook<IntelligentNote> note2=new Notebook<>();
        try{
        Note<IntelligentNote> n4=new Note<>(new IntelligentNote("Math", Days.FRIDAY, 3));
        Note<IntelligentNote> n5=new Note<>(new IntelligentNote("English", Days.MONDAY, 2));
        Note<IntelligentNote> n6=new Note<>(new IntelligentNote("Informatik", Days.THURSDAY, 1));
        note2.addNote(n4);
        note2.addNote(n5);
        note2.addNote(n6);
        note2.printToDoList();
        }catch(Exception e)
        {
            e.getMessage();
        }

        
        

    }
}

