/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package io.fp.container;

import java.util.ArrayList;

public class App {

    public static void main(String[] args) {
        Container<Clothes> clothesContainer = new Container<>();
        Container<ElectricalDevices> electricalDeviceContainer = new Container<>();
        Container<? super Cargo> mixedContainer = new Container<>();

        Clothes juveJersy = new Clothes("Juventus Turin Trikots", 500);
        Clothes barcaJersy = new Clothes("FC Barcelona Trikots", 500);
        Clothes bayernJersy = new Clothes("Bayern Muenchen Trikots", 500);

        ElectricalDevices smartphones = new ElectricalDevices("Smartphones", 800);
        ElectricalDevices monitor = new ElectricalDevices("Monitore", 800);
        ElectricalDevices laptop = new ElectricalDevices("Laptops", 800);

        Clothes blueShirts = new Clothes("Blaue T-Shirts", 300);
        Clothes blackShirts = new Clothes("Schwarze T-Shirts", 200);
        ElectricalDevices microwave = new ElectricalDevices("Microwelle", 800);
        ElectricalDevices toaster = new ElectricalDevices("Toaster", 800);

        
        try {
            System.out.println("Load Clothes Container");
            clothesContainer.loadCargo(juveJersy);
            clothesContainer.loadCargo(barcaJersy);
            clothesContainer.loadCargo(bayernJersy);
            System.out.println("----------------------");
        } catch (CargoException e) {
            System.out.println(e.getMessage());
        }

        //Try load ElectricalDeviceContainer
        try {
            System.out.println("Load Electronical Device Container");
            electricalDeviceContainer.loadCargo(smartphones);
            electricalDeviceContainer.loadCargo(monitor);
            electricalDeviceContainer.loadCargo(laptop);
            System.out.println("----------------------");
        } catch (CargoException e) {
            System.out.println(e.getMessage());
        }

        //Try load mixedContainer
        try {
            System.out.println("Load mixed Container");
            mixedContainer.loadCargo(blueShirts);
            mixedContainer.loadCargo(blackShirts);
            mixedContainer.loadCargo(microwave);
            mixedContainer.loadCargo(toaster);
            mixedContainer.loadCargo(smartphones);
        } catch (CargoException e) {
            System.out.println(e.getMessage());
        }

        System.out.println("--------------------------");
        System.out.println(clothesContainer);
        System.out.println(electricalDeviceContainer);
        System.out.println(mixedContainer);

        Ship ship = new Ship();
        ArrayList<Container<? extends Cargo>> containers = new ArrayList<>();
        Container<Clothes> container1 = new Container<>();
        Container<ElectricalDevices> container2 = new Container<>();
        Container<Clothes> container3 = new Container<>();
        Container<Clothes> container4 = new Container<>();
        Container<Clothes> container5 = new Container<>();
        Container<Clothes> container6 = new Container<>();
        Container<Clothes> container7 = new Container<>();
        Container<Clothes> container8 = new Container<>();
        Container<Clothes> container9 = new Container<>();
        try {
        System.out.println("Load cargo to containers: \n");
        container1.loadCargo(new Clothes("Blaue T-Shirts", 2700));
        container2.loadCargo(new ElectricalDevices("Smartphones", 2700));
        container3.loadCargo(new Clothes("Juventus Turin Trikots", 2700));
        container4.loadCargo(new Clothes("Hosen", 2700));
        container5.loadCargo(new Clothes("Hoodies", 2700));
        container6.loadCargo(new Clothes("Socken", 2700));
        container7.loadCargo(new Clothes("Schuhe", 2700));
        container8.loadCargo(new Clothes("Schwarze T-Shirts", 2700));
        container9.loadCargo(new Clothes("Rote T-Shirts", 2700));
        containers.add(container1);
        containers.add(container2);
        containers.add(container3);
        containers.add(container4);
        containers.add(container5);
        containers.add(container6);
        containers.add(container7);
        containers.add(container8);
        containers.add(container9);
        System.out.println("--------------------");
        } catch (CargoException e) {
        System.out.println(e.getMessage());
        }
        ArrayList<Container<? extends Cargo>> loadedContainers = ship.registerContainer(containers);
        System.out.println("\n Containers loaded to ship: ");
        System.out.println(ship.getRegisteredContainters());
        containers.removeAll(loadedContainers);
        System.out.println("\n Container not loaded - ship capacity exceeded: ");
        System.out.println(containers);
    }
    
    

}
