/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package io.fp.campus;

public class App {

    public static void main(String[] args) {
        
        Faculty hogwarts = new Faculty("Hogwarts");

        Professor dumbledore = new Professor("Dumbledore", 77, "BPM", hogwarts);
        System.out.println(dumbledore.getName());
        System.out.println("Hält er Vorlesung? "+dumbledore.isTalking());
        dumbledore.setTalking(false);
        System.out.println("Hält er Vorlesung? "+dumbledore.isTalking());

        Assistent hagrid = new Assistent("Hagrid", 26, hogwarts);
        hagrid.setBoss(dumbledore);
        System.out.println(hagrid.getName());
        System.out.println(hagrid.getBoss().getName());

        Assistent dobby = new Assistent("Dobby", 130, hogwarts);
        dobby.setBoss(dumbledore);

        Assistent pince = new Assistent("Madam Pince", 50, hogwarts);
        
        hogwarts.addProfessor(dumbledore);
        hogwarts.addAssistent(hagrid);
        hogwarts.addAssistent(dobby);
        hogwarts.addAssistent(pince);

        System.out.println("Fakultät "+ hogwarts.getName());
        System.out.println(hogwarts.getProfs().toString());
        System.out.println(hogwarts.getAssis().toString());

        System.out.println(hogwarts.getAssisOfProf(dumbledore));

        System.out.println(hogwarts.getProfsWithAssis());

        System.out.println("Anzahl Profs: " + hogwarts.getAmountProfs());

        System.out.println("Anzahl Assis: " + hogwarts.getAmountAssis());
    }
}

