/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package io.fp.lottery;

public class App {
   

    public static void main(String[] args) {
        try {
            LotteryTicket ticket1 = new LotteryTicket("Luca", 1,2,4);
            LotteryTicket ticket2 = new LotteryTicket("Jannik", 3,1,5);
            LotteryTicket ticket3 = new LotteryTicket("Fatih", 1,3,2);
            LotteryTicket ticket4 = new LotteryTicket("Dario", 2,1,5);

            Lottery lottery = new Lottery(3, 5);

            lottery.submitTicket(ticket1);
            lottery.submitTicket(ticket2);
            lottery.submitTicket(ticket3);
            lottery.submitTicket(ticket4);

            System.out.println("Lottery Draw");
            lottery.lotteryDraw();

            System.out.println("-----------------------");
            ticket1.printLotteryStatistic(lottery.getDrawedNumbers());
            System.out.println("-----------------------");
            ticket2.printLotteryStatistic(lottery.getDrawedNumbers());
            System.out.println("-----------------------");
            ticket3.printLotteryStatistic(lottery.getDrawedNumbers());
            System.out.println("-----------------------");
            ticket4.printLotteryStatistic(lottery.getDrawedNumbers());

        } catch (LotteryException e) {
           System.out.println(e.getMessage());
        }

        
    }
}
