/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package io.fp.bmiCalculatorFX.ui;

import java.io.IOException;
import java.util.List;

import io.fp.bmiCalculatorFX.dao.BMICalculatorDAO;
import io.fp.bmiCalculatorFX.dao.TextDaoImpl;
import io.fp.bmiCalculatorFX.model.BMICalculatorException;
import io.fp.bmiCalculatorFX.model.CategoryException;
import io.fp.bmiCalculatorFX.model.HealthCheck;
import javafx.application.Application;
import javafx.scene.Parent;
import javafx.scene.Scene;
import javafx.scene.control.Button;
import javafx.scene.control.Label;
import javafx.scene.control.TextField;
import javafx.scene.layout.BorderPane;
import javafx.scene.layout.FlowPane;
import javafx.scene.paint.Color;
import javafx.stage.Stage;

public class HeathCheckUI extends Application {

    private TextField weightTextField;
    private TextField heightTextField;
    private Button execute;
    private Button showStatistics;
    private Button clear;
    private Label calculationLabel;
    private Label statisticLabel;
    private Label avgLabel;

    // model
    private HealthCheck healthCheck;
    // dao
    private BMICalculatorDAO dao;

    @Override
    public void init() throws Exception {
        // init dao
        Parameters params = getParameters();
        List<String> paramList = params.getRaw();
        if (paramList.size() < 1) {
            throw new IOException("No parameter defined for file name!");
        }
        dao = new TextDaoImpl(paramList.get(0));

        // init model
        try {
            healthCheck = dao.createStore();
        } catch (IOException e) {
            healthCheck = dao.readStore();
        }

        // Initiate labels
        healthCheck = new HealthCheck();
        statisticLabel = new Label("");
        avgLabel = new Label("");
        calculationLabel = new Label("");

        // Initiate textfields
        weightTextField = new TextField();
        weightTextField.setPrefColumnCount(10);
        weightTextField.setPromptText("Enter weight here!");

        heightTextField = new TextField();
        heightTextField.setPrefColumnCount(10);
        heightTextField.setPromptText("Enter height here!");

        // Initiate buttons
        execute = new Button("Execute Healthcheck");
        execute.setOnAction(e -> {
            double weight = Double.parseDouble(weightTextField.getText().trim());
            double height = Double.parseDouble(heightTextField.getText().trim());
            try {
                calculationLabel.setText(healthCheck.executeHealthCheck(weight, height));
                dao.updateStore(healthCheck);
            } catch (CategoryException | BMICalculatorException | IOException e1) {
                System.out.println(e1.getMessage());
            }
        });

        clear = new Button("Clear");
        clear.setOnAction(e -> {
            calculationLabel.setText("");
            statisticLabel.setText("");
            avgLabel.setText("");
        });

        showStatistics = new Button("Show Statistics");
        showStatistics.setOnAction(e -> {
            try {
                healthCheck = dao.readStore();
                statisticLabel.setText(healthCheck.getCategoryStatistics());
                avgLabel.setText(healthCheck.getAverageBMI());
                statisticLabel.setTextFill(Color.BLACK);
            } catch (IOException e2) {
                statisticLabel.setTextFill(Color.RED);
                statisticLabel.setText(e2.getMessage());
                System.out.println(e2.getMessage());
            }
        });

    }

    private Parent createSceneGraph() {
        FlowPane top = new FlowPane();
        FlowPane bottom = new FlowPane();
        FlowPane center = new FlowPane();

        top.getChildren().addAll(weightTextField, heightTextField, execute);
        center.getChildren().addAll(calculationLabel, statisticLabel, avgLabel);
        bottom.getChildren().addAll(showStatistics, clear);

        BorderPane border = new BorderPane();
        border.setTop(top);
        border.setBottom(bottom);
        border.setCenter(center);

        return border;
    }

    @Override
    public void start(Stage primaryStage) throws Exception {
        primaryStage.setTitle("BMI Calculator");
        Scene scene = new Scene(createSceneGraph(), 600, 200);
        primaryStage.setScene(scene);
        primaryStage.show();
    }

    public static void main(String[] args) {
        launch(args);
    }

}
